std = "lua51"

exclude = [
  "src/lib/*",
  "src/lib/**/*",
  "tests/*",
  "tests/**/*",
  ".luarocks/*",
  ".luarocks/**/*",
  ".git/*"
]

[rules]
unused_variable = "allow"
shadowing = "warn"
multiple_statements = "allow"
empty_if = "deny"
empty_loop = "deny"
duplicate_keys = "deny"
unscoped_variables = "allow"
undefined_variable = "allow"
mixed_table = "allow"
global_usage = "allow"




